[package]
name = "bitly"
version = "0.1.0"
authors = ["Siobhán Sterrett <siobhan.sterrett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "1.4", features = ["postgres"] }
dotenv = "0.15"
rand = "0.7"
